### ISSUE TITLE
First setup phase is always showing first

### ISSUE THREAD

**Issue by os-micmec** [google/ground-platform#1119]
**Describe the bug**
When we are in the process of creating/editing a survey, we have code that lands us on the most relevant (current) phase of the process depending on what data was already submitted. The problem is that, while the UI is deciding what is the most relevant phase, we are showing the initial one to the user.

**To Reproduce**
1. Create e new survey
2. Add a survey name and description and go to the next phase
3. Refresh. You should see the first phase for a split of a second

**Expected behavior**
We should have a loading bar while we are deciding state.

**Comment by gino-m** [comment]
This issue appears to be due to the fact that the current survey is handled reactively, but the update doesn't propagate before we move to the next page.

Suggested fixes to CreateSurveyComponent:

- [ ] Don't react to server-side changes to survey - load on init instead
- [ ] Update state of in-memory survey after each step (not just in db)

@rfontanarosa PTAL?
