### ISSUE TITLE
[Code health] Disambiguate difference between TaskType and TaskGroup

### ISSUE THREAD

**Issue by os-micmec** [google/ground-platform#1163]
At the moment, we have the following two types in our code;

In `task.model.ts`:
```
export enum TaskType {
  TEXT = 1,
  MULTIPLE_CHOICE = 2,
  PHOTO = 3,
  NUMBER = 4,
  DATE = 5,
  TIME = 6,
}
```

and in `task-details.component.ts`:

```
export enum TaskGroup {
  QUESTION = 1,
  PHOTO = 2,
  DROP_PIN = 3,
  DRAW_AREA = 4,
  CAPTURE_LOCATION = 5,
}
```

We should rethink of their name and/or usage, because seeing two variables defined by these two types is confusing.

**Comment by rfontanarosa** [comment]
I don't know how much invasive this change will be, but probably we should separate TaskType (current TaskGroup) from AnswerType (current TaskType).

it seems that the current TaskType (Text, Number, Date, Time) is used to validate the answer but it can be edited only for the QUESTION.

moreover, at the moment we don't have a way to show/hide the TEXT/NUMBER/etc. selector because the TaskGroup is not saved.

another thing: the current enum TaskType not corresponds with the list shown in the mock.

what do you think?
