### ISSUE TITLE
[Code health] Extract the spinner and  the logic that reads survey into a component

### ISSUE THREAD

**Issue by DaoyuT** [google/ground-platform#1170]
As suggested https://github.com/google/ground-platform/pull/1167#discussion_r1323246012

**Comment by gino-m** [comment]
My original idea creating a container component which includes child content using content projects (`<ng-content>`), and passing the current survey to children using Angular's `@Input` fell through, since `ng-content` projects the child's HTML without implementing any of Angular's data binding and related updates. tl;dr: `ng-content` doesn't work with `@Input`. Closing in favor of #1191.
