### ISSUE TITLE
[Submission details] Display elevation and accuracy for capture location

### ISSUE THREAD

**Issue by amysorto** [google/ground-platform#1329]
Right now capture location tasks are treated the same as a point. Although they have some additional data (elevation and accuracy), but it is not shown anywhere.

**Comment by gino-m** [comment]
@vittorino How would this look in the submission panel?

**Comment by vittorino** [comment]
here's an example of how it should look:
<img width="431" alt="image" src="https://github.com/google/ground-platform/assets/679199/c781f4f8-2536-448f-8a3c-e4f5ee6a4a81">

**Comment by gino-m** [comment]
The point would also show on the map like with "Drop a pin" tasks. Should this marker also be included here, maybe with a different icon to indication GPS location instead of manual?

<img width="256" alt="image" src="https://github.com/google/ground-platform/assets/228050/49f5d2dc-508a-48e6-8d82-653a59eeb115">

**Comment by gino-m** [comment]
This doesn't appear to be in the db, or the format aren't consistent. Punting to next iteration.

**Comment by shobhitagarwal1612** [comment]
Yes, we do store elevation in the "Capture location" tasks.
