### ISSUE TITLE
Remove home on edit survey

### ISSUE THREAD

**Issue by jcqli** [google/ground-platform#1500]
@gino-m Any additional context?

**Comment by gino-m** [comment]
The "Home" button is duplicate with "Cancel". The latest designs removed that:

![image](https://github.com/google/ground-platform/assets/228050/bf81b4d1-2494-40a8-a301-d6f8b7c03956)


I would also suggest that "Publish changes" returns the user to the home screen, since most users usually click "Publish changes" immediately followed by "Cancel" anyway.

**Comment by rfontanarosa** [comment]
closed by https://github.com/google/ground-platform/pull/1555
