### ISSUE TITLE
[LOI Editor] Imported LOIs not shown on map when importing for new unpublished job

### ISSUE THREAD

**Issue by gino-m** [google/ground-platform#1714]
@nwkotto @DaoyuT @rfontanarosa

**Comment by jcqli** [comment]
@DaoyuT What is the proposed plan for this change?

**Comment by DaoyuT** [comment]
#### To reproduce
 - Create a new job
 - Import LOIs for that new job

Expect to see the imported LOIs on the map, but they don't show up.

#### Reason

When the job is not published, those LOIs are uploaded but associated with any job, so the map component won't render them.

#### Proposed solution

2 ways depends on if we want to bundle the import/delete LOI action within the publish job action:

If we want them together(more complex fix)
 - Add a state to each LOI and manage the states so that in the edit job phase
   - user import LOIs, LOIs shows in edit page, user clicks publish button, LOIs shows in map page
   - user import LOIs, LOIs shows in edit page, user quits editing without clicking publish, LOIs does not show in map page
   - user delete LOIs, LOIs does not show in edit page, user clicks publish button, LOIs does not show in map page
   - user delete LOIs, LOIs does not show in edit page, user quits editing without clicking publish, LOIs shows in map page
   - same behavior should happen to a new unpublished job


If we are okay with them separated(easier fix)
 - Make sure the imported LOIs for the new unpublished job are associated with the job id and can reach the map component

**Comment by jcqli** [comment]
FYI @gino-m , more context above. WDYT about the easier solution?

**Comment by gino-m** [comment]
Hi @DaoyuT @jcqli It sounds like we won't have time for the full fix by Beta launch this month; let's go for option 2, and file a follow up FR to implement "publish" of LOI changes (import, delete)?

**Comment by gino-m** [comment]
@DaoyuT Has there been any progress on this issue?

**Comment by gino-m** [comment]
@sufyanAbbasi, @rfontanarosa mentioned you'd like to take this one on. Do you have a sense how many days work it would be to fix?

**Comment by sufyanAbbasi** [comment]
For me, between 3-4 days, mostly just investigation and getting myself acclimated to the codebase.

**Comment by sufyanAbbasi** [comment]
Having played around with it, I noticed that we could create the job when the "new job" button is pressed, just like when we create the initial job in the survey, as we also preemptively create an initial job during the survey creation flow. Then we'll have a Job ID available to bind the uploaded LOIs to?

**Comment by gino-m** [comment]
> Having played around with it, I noticed that we could create the job when the "new job" button is pressed, just like when we create the initial job in the survey, as we also preemptively create an initial job during the survey creation flow. Then we'll have a Job ID available to bind the uploaded LOIs to?

Unfortunately that would trigger an update to clients of a new job being added before the user actually clicks "Publish". I think the easiest workaround is to warn the user that importing LOIs will cause the job to be immediately .

**Comment by sufyanAbbasi** [comment]
I see, that makes sense. On further notice, I found that `onImportLocationsOfInterest()` which executes on "Upload" seems to use the `DataImportService` rather than the `DraftSurveyService`, seems like we're bypassing the mechanism that handles this stuff. Maybe a little bit of refactoring there to make `DraftSurveyService` more LOI aware can get us most of the way there?

**Comment by gino-m** [comment]
@sufyanAbbasi, @jcqli, just heard back from @DaoyuT - he plans to take a look at this next week. I think he already has a workaround in mind, so might be better to wait for him?

**Comment by DaoyuT** [comment]
Fixed by PR #1958
Opened bug #1964 for future improvement
