### ISSUE TITLE
[Code health] Front-load anticipated breaking changes before Beta release

### ISSUE THREAD

**Issue by gino-m** [google/ground-platform#1762]
This includes:

- [x] https://github.com/google/ground-platform/issues/1703
  - [x] https://github.com/google/ground-android/issues/2431
- [x] https://github.com/google/ground-platform/issues/1761
- [x] https://github.com/google/ground-platform/issues/936
- [x] https://github.com/google/ground-platform/issues/1288
- [x] https://github.com/google/ground-platform/issues/1536

@jcqli FYI

@rfontanarosa @shobhitagarwal1612 @sufyanAbbasi FYI

**Comment by jcqli** [comment]
Synced with @gino-m to clean up some of this task tracking:

- The top half tasks under "This includes:" will be addressed by the protobuf migration. Let's leave them open as outstanding issues but close them out via the migration tasks
- We'll move the migration tasks under "Migration plan:" to be tracked by #1758 as the parent issue. It will track issues across both repos so that we can execute them in order as needed.

I'll make these changes to cleanup our issue tracking

**Comment by gino-m** [comment]
All related work on this issue is being handled as part of #1758.
