### ISSUE TITLE
Questions about e2e-tests/package.json

### ISSUE THREAD

**Issue by gino-m** [google/ground-platform#1811]
Hi @sufyanAbbasi! I had a few questions, collecting them here:

* `gts clean` won't work if `gts` isn't already installed, whereas our "clean" command in order packages also deletes node_modules. Not sure what standard practice is, but we should do the same thing in all "clean" scripts.
* Why do we need tsx + relative path to bin rather than just `jasmine creation-survey.spec.ts`? Can we simplify?
* The code seems to run lint on itself after running e2e tests. Can we define e2e tests in the "run" part of the lifecycle rather than in "test" one?
*  Iuuc, the "prepare" hook is only for when the dir is symlinked, in which case we don't need that script
* The "build" script just runs "install". Is that intentional?
* Why do we need `--legacy-peer-deps` on `npm i`?

**Comment by sufyanAbbasi** [comment]
I finally got around to submitting the package updates in https://github.com/google/ground-platform/pull/1820 that hopefully resolve some of the questions here!

> gts clean won't work if gts isn't already installed, whereas our "clean" command in order packages also deletes 
node_modules. Not sure what standard practice is, but we should do the same thing in all "clean" scripts.

Good call, thank you for removing it.

> Why do we need tsx + relative path to bin rather than just jasmine creation-survey.spec.ts? Can we simplify?

When I run `jasmine creation-survey.spec.ts`, I get `cannot use ESModules...` error which is weird because the package is defined as a module, and when I try running it from `bin` without `tsx`, I get: `'jasmine' module not found`. Or I also tried running jasmine on the js binary at build, but that didn't work either :P. Finally, the advantage to using `tsx` is that we don't actually need to compile the TS code, which was removed, and it supports `--inspect` natively for debugging.

> The code seems to run lint on itself after running e2e tests. Can we define e2e tests in the "run" part of the lifecycle rather than in "test" one?

That was weird boilerplate, removed.

> Iuuc, the "prepare" hook is only for when the dir is symlinked, in which case we don't need that script

More weird boilerplate, removed.

> The "build" script just runs "install". Is that intentional?

Yes! Since we don't need to compile scripts when using `tsx`.

>Why do we need --legacy-peer-deps on npm i?

We don't, removed.
