### ISSUE TITLE
[LOI Editor] Importing LOIs for new unpublished job will end up having unassociated LOIs if user end up not publishing the job

### ISSUE THREAD

**Issue by DaoyuT** [google/ground-platform#1964]
For bug #1714, we did a quicker fix #1958 that shows LOIs imported for new unpublished job. However, if user don't publish the job after importing LOIs, those LOIs would still exist with no job associated to it. Although they won't be rendered in the map view since they don't belong to any valid job, it's still bad to have these useless data sitting in the database.

One solution is to delete these LOIs that don't belong to any valid job every time the user hits the publish button.
On top of that we could also bundle the import/delete LOI action within the publish job action, like mentioned in bug #1714.

**Comment by jcqli** [comment]
Copying over more info from https://github.com/google/ground-platform/issues/1895:

When LOIs are imported for a job that is not published, they do not show up in the map as they are not associated with any jobs.

We can bundle the import/delete LOI action within the publish job action:

[ ] Add a state to each LOI and manage the states so that in the edit job phase
[ ] user import LOIs, LOIs shows in edit page, user clicks publish button => LOIs shows in map page
[ ] user import LOIs, LOIs shows in edit page, user quits editing without clicking publish => LOIs does not show in map page
[ ] user delete LOIs, LOIs does not show in edit page, user clicks publish button => LOIs does not show in map page
[ ] user delete LOIs, LOIs does not show in edit page, user quits editing without clicking publish => LOIs shows in map page
[ ] Same behavior should happen to a new unpublished job

More context: https://github.com/google/ground-platform/issues/1714#issuecomment-2200410314

**Comment by kenstershiro** [comment]
From @rfontanarosa - this should be solved now when you click publish they get cleaned up
