### ISSUE TITLE
[Map] Add new point feature to map

### ISSUE THREAD

**Issue by gino-m** [google/ground-platform#251]
Ability to add a new point to the map. @jacobmclaws, how will the user select the layer and location for new points? Whatever solution we come up with should also scale to drawing polygons eventually.

**Comment by gino-m** [comment]
Reassigning to PM @sergeydolgov1. @jacobmclaws please accept new invite to repo so I can also assign to you. Will assign back to eng once the CUJ is defined.

**Comment by gino-m** [comment]
@sergeydolgov1 @jacobmclaws Gentle ping:

> How will the user select the layer to which to add new points?

Please paste mocks here for @DaoyuT.

**Comment by sergeydolgov1** [comment]
@gino-m @DaoyuT 

A) User clicks on the layer for which they want to add Point:
![image](https://user-images.githubusercontent.com/20148684/87334503-9ab6f500-c4f3-11ea-998f-721443ab32a7.png)

**Comment by sergeydolgov1** [comment]
@gino-m @DaoyuT 

B) To add new Point user clicks on the Point button in the lower left corner 
![image](https://user-images.githubusercontent.com/20148684/87334632-cfc34780-c4f3-11ea-9594-ac7f9f7efdec.png)

**Comment by gino-m** [comment]
@sergeydolgov1 Could you kindly paste the mock here?

**Comment by sergeydolgov1** [comment]
@gino-m @DaoyuT 
This is the latest mock (see the link below)
Question from Jacob: _"Is it possible to have some smarts about which layer a user was looking at in the side panel and defaulting to that layer when they create or will it always just be the top layer in the list?"_ [This feature would be optional]
[Add New Point.pdf](https://github.com/google/ground-platform/files/4963832/Add.New.Point.pdf)

**Comment by gino-m** [comment]
@sergeydolgov1 Thanks again for the wireframe! @jacobmclaws Could you a provide actual updated mocks for this flow and the "polygon" icon asset as well?

**Comment by gino-m** [comment]
From @sergeydolgov1 (moved from https://github.com/google/ground-android/issues/358#issuecomment-671541451):

> Prioritized drawing a polyline (Lines + Polygons) for RC1. Latest mocks below:
>
> ![image](https://user-images.githubusercontent.com/20148684/89821845-18c2e780-db04-11ea-8c31-b07b0fdfb8e0.png)
>
> ![image](https://user-images.githubusercontent.com/20148684/89821861-211b2280-db04-11ea-9f66-85103f5ca9b7.png)

**Comment by mmisim** [comment]
@jacobmclaws — What do you think about adding a persistent banner at that top of the screen, below the project name, when the user is in add point/polygon mode? I'm not sure if it would be better or worse than the floating layer dropdown that's currently implemented, but if we have multiple interactions that we need to expose for the add mode (e.g. layer select, cancel, maybe single/multi point add), it might make sense to group them into a single banner, rather than have multiple floating elements on the map.
It would also allow us to be more explicit about the current state because there would be space to include a label like:
**You are adding a point to the <layer dropdown> layer.**
If this isn't clear, ping me and I can send you an example of what I had in mind.
