### ISSUE TITLE
[Manage Project] Specify the URL of a tile base map source for offline download in the Android client

### ISSUE THREAD

**Issue by sergeydolgov1** [google/ground-platform#372]
Managers may specify the URL of a tile base map source for offline download in the Android client

Potential user flow:
1. Manager selects the option to create URL for a tile base map
2. Manager selects a tile base map (can be currently visible map area)
3. Manager confirms selected tile/ map area
4. URL is generated, can be accessed in a dedicated place, e.g. under Project's ellipsis (three dots). Manager should be able to delete the link if needed
5. URL is visible in the Android app

**Comment by gino-m** [comment]
Offline tile sources can't actually be generated by Ground - the idea for configuring the offline data sources was that if a user or org has the capacity and data to generate their own, they would drop them on an HTTP server or in Google Cloud Storage along with a GeoJSON file with the extents of each tileset and respective mbtiles URL. They would then provide the URL of that "footprints" file to Ground for use in the Android app. In this case, setting the offline tile source is really a question of pasting the URL into a modal Project Settings dialog or similar. HTH!

**Comment by sergeydolgov1** [comment]
The way I thought about it is that Project manager suggests an area of base map that can be downloaded by Collectors for offline usage. That way Collectors do not need to figure out themselves which area they need to download, they get just the right tile that covers all layers and features

**Comment by gino-m** [comment]
Ah, I see. This is also a possibility, but I'm not sure what the usual use pattern will be. I think it mostly depends on the scale of the project; if a project will be covering a larger area, users may want to load only the area they'll be visiting rather than the whole map specified by the project manager. We started by allowing the user to specify themselves since covers both cases (larger and smaller scale projects).

+1 this being a P3 for now; I agree this could be useful to look into after we get through pilots!

**Comment by gino-m** [comment]
Closing as obsolete for now.
