### ISSUE TITLE
[Map] Indicate features with observations on map

### ISSUE THREAD

**Issue by gino-m** [google/ground-platform#762]
Requested by @kdyson. @coreyleamon @jacobmclaws Do you have any suggestions on how to do this? For markers I would imagine we would overlay a bubble with the number of observations, but what about polygons? Ideally the same solution would work both on web and mobile (See also https://github.com/google/ground-android/issues/893).

**Comment by coreyleamon** [comment]
I'd like to understand the user need a little better before making a suggestion.  Is the ask about knowing the exact number of observations or is it about knowing if there are any at all vs an empty point/poly? And what problem does having this knowledge from the map view solve? Thanks!

**Comment by kdyson** [comment]
Mostly I'm looking for a visual marker that a specific map polygon has had data collected for it. So for this project, we have multiple plots for each location. It would be helpful to see quickly which have had data collected vs partly collected vs. not collected.

**Comment by coreyleamon** [comment]
I see - can you help me understand what "partly collected" or "completed"
would mean? And what does having this knowledge help a user do?

I ask because the system cannot inherently know if data is incomplete.
Therefore, a couple opportunities come to mind for me:
1) communicate the number of added observations, leaving it up to the user
to know whether that number equates to incomplete or complete documentation
2) allow the user to indicate a progress state for a point or polygon,
requiring they manually change status from "in progress" to "complete" when
all data has been added (this can act as a way to double-check data before
committing it, as well)

Thanks for your insight!

**Comment by gino-m** [comment]
@coreyleamon I think @kdyson is referring to which of the subplots have observations vs. not. In this case, a "1" on all four subsamples, "1" on each plot, and "1" on the field/farm, would indicate the work was complete. @kdyson Is that correct?

**Comment by kdyson** [comment]
Hm, on revisiting this i think partly collected doesn't make sense since you can't save a plot without all required questions answered.

What I'm thinking is a visual marker to indicate which polygons or points you have collected data for vs. not. One example would be if you have NOT collected data for a polygon it has a dashed outline and if you HAVE collected data for a polygon it has a solid outline.

**Comment by gino-m** [comment]
Obsolete.
