### ISSUE TITLE
Improve Ground nomenclature

### ISSUE THREAD

**Issue by gino-m** [google/ground-platform#81]
Both testers and developers have often been confused by some of the terminology used in Ground. Let's fix this by replacing the more obscure ones with more self describing terms, rescoping where it would help usability.

I've added the current definitions to the Wiki as a placeholder / basis for discussion [here](https://github.com/google/ground-platform/wiki/Core-Concepts). I'll only address the ones reported as troublesome here:

1. **Feature Type vs Feature** - Feature Type is currently scoped as a "class" or "template" for new map Features, specifying a name (e.g. Household), default marker/line style, and a Form layout. Users are often confused between Feature Type (the metadata/project config) and Feature (instances shown on map). It's not clear how "Feature Type" should be represented in the UI to differentiate them from Features themselves.
1. **Form vs Record** - so far we've been calling the layout of the form Form, and the instances (completed forms, i.e. data) as Records. "Add Record" in the UI is not really intuitive or elegant, and editing a Form is sometimes confused with filling out a Form with data.

I'll put my two cents in comments below. Assigning to @hintzemichael for UX, @raleigh-s as PgM representing user requirements ("owner"), and @scolsen for tech. writing and data modeling.

**Comment by scolsen** [comment]
I think the more concrete and specialized we can make our terms the better (though we're dealing with inherently abstract entities here, so this is difficult).

I'm still thinking about Form/Record, but for Feature, here are two ideas:

**Landmark Template** and **Landmark**
Landmark is still an abstract term (it can conceivably denote any mapped object)  but it is more specialized than feature. A landmark typically denotes an "object" of sorts whereas a map "feature" may denote e.g. a property of a terrain (the elevation of a mountain is a feature of the landscape rendered on a map). I think landmark better captures the fact that the objects we're mapping are usually fixed objects in space, as opposed to features of the terrain.

Here's the definition of landmark from [utexas glossary of cartography terms](https://legacy.lib.utexas.edu/maps/glossary.html):

> Monument of material mark or fixed object used to designate a land boundary on the ground: any prominent object on land that may be used to determine a location or a direction in navigation or surveying.

I think we have potential use-cases that don't totally map to that definition (e.g. time series analysis related stuff, mobile entities, like wolf packs or population shifts), but I think it's a better fit for most "static" use cases (households, resources, etc.). 

I think "Template" is easier to understand than "type" or "class" for most people (I have no data to support this claim, however). Type and class are terms that derive their meaning from the context of predicate logic and mathematics. Template is also frequently used in many applications when one is specifying an instantiable class of entity or entity with preset properties (e.g. google docs, etc.)[^1]

or

**Feature Template** and **Feature** 
We could just stick with feature and try "template" instead of "type". I'm not sure if the confusion is mostly deriving from the type/instance distinction or from the abstractness of the term feature itself.

[^1]: Let the record state that my *personal* preference lays strongly with type and class. Template is an ugly, antiquated word that reeks of the industrial era. In spite of this, I do believe more users would understand this wretched word.

**Comment by gino-m** [comment]
Thanks for the suggestions! My comments: 
> Landmark Template and Landmark

These unfortunately have special meaning in the context of many of our projects and would lead to extra confusion. "Map feature" is a pretty well established term in digital mapping; I fear rebranding it will be to the user's detriment. That said, I don't think we'll ever need to show the word "feature" in the UI if we rebrand "feature type". 

> Let the record state that my personal preference lays strongly with type and class. Template is an ugly, antiquated word that reeks of the industrial era. In spite of this, I do believe more users would understand this wretched word.

Haha, I tend to agree. "Template' implies a "copy" is made, and that some data can be prefilled, which isn't the case.

**Comment by gino-m** [comment]
> 1. Feature Type vs Feature - Feature Type is currently scoped as a "class" or "template" for new map Features, specifying a name (e.g. Household), default marker/line style, and a Form layout. Users are often confused between Feature Type (the metadata/project config) and Feature (instances shown on map). It's not clear how "Feature Type" should be represented in the UI to differentiate them from Features themselves.

In place of feature type, Michael's latest mocks use the term/concept *layers*, which a common feature of nearly all modern GISes:

![image](https://user-images.githubusercontent.com/228050/59700020-90c3a500-91c0-11e9-89d1-c89bbf0855b6.png)

This also fits well with our need to eventually show static custom vector layers. If we rethink Feature Type slightly, it should be possible to cast them as layers as well. It would go something like this:

Managers would add and customize layers when configuring a project. For each layer, they would define a name, and optionally, a default style for vectors, a form, and whether contributors should be able to add points, lines, and/or polygons. In future versions, managers should be able to import arbitrary vectors for display only (e.g. park boundaries, ecological zones, etc.), or as preloaded features for observation.

> 2. Form vs Record - so far we've been calling the layout of the form Form, and the instances (completed forms, i.e. data) as Records. "Add Record" in the UI is not really intuitive or elegant, and editing a Form is sometimes confused with filling out a Form with data.

In Ground, collaborators are effectively making *observations* about map features. In that case, it might make sense to just call them as such. For consistency and clarity, we could also rebrand the Form as Observation Form. This would also allow us to introduce Feature-level attributes in the future through something like Feature Forms if it turns out to be necessary.

**Comment by scolsen** [comment]
I like *Layers*! 

@gino-m  to clarify, you're suggesting we rename *form* and *record* to *observation form* and *observation*?

**Comment by gino-m** [comment]
> @gino-m to clarify, you're suggesting we rename form and record to observation form and observation?

Suggesting the following:

1. Feature type ➡ Layer
2. Form ➡ Observation form
3. Record ➡ Observation

**Comment by scolsen** [comment]
Cool! I'm fine with that. Is `Observation Form` going to be exposed in the UI at all? If so, just calling it `Form` in the UI might make it easier to scan.

Does that mean we may eventually have `Observable<Observation>`s :stuck_out_tongue:

**Comment by gino-m** [comment]
> Is Observation Form going to be exposed in the UI at all? If so, just calling it Form in the UI might make it easier to scan.

If we don't have any other type of for I agree just saying "Form" would be sufficient. But both options can be available to UX depending on what's clearer. @hintzemichael FYI.

> Does that mean we may eventually have Observable<Observation>s 😛

Nope, only `Flowable<Observation>` and `Observable<Flow>`, I promise 😉

**Comment by gino-m** [comment]
@raleigh-s and I discussed this with PMs of related Google products in an effort to harmonize nomenclature, diverging where it makes sense. Key takeaways:

* Everyone agreed `Layer` was a familiar concept and works in this context, provided there's a way to distinguish layers Contributors can add features to vs. those that only Managers can modify. In the project config we'll add checkboxes akin "Allow contributors to add [ ] points [ ] lines [ ] polygons".
* Several ideas were discussed, but ultimately everyone agreed `Observation` was a better choice than `Record`. It also scales to observations collected looking at satellite basemaps via the web app. It's specific enough to be clear but general enough to apply to all know scenarios.
* It wasn't clear to everyone whether `Form` meant a completed form with data (our `Record`), or a Form layout. We should qualify Form with a verb or subtitle in the UI to make this clear, e.g. "Observation form" with subtitle "Define the form used for collecting observations about features in this layer.

Filed #79, http://go/gh/google/ground-android/issues/121 to update UI.

Will close this issue once we update the Wiki with the new terms and file tickets to update the code and db.

**Comment by gino-m** [comment]
@scolsen @dhvogel I've updated https://github.com/google/ground-platform/wiki/Key-Concepts to reflect this and other discussions. Could you PTAL to see if it's clear?

**Comment by gino-m** [comment]
Remaining tasks forked into separate issues:
* https://github.com/google/ground-platform/issues/79
* https://github.com/google/ground-platform/issues/88
* https://github.com/google/ground-platform/issues/87
* https://github.com/google/ground-android/issues/121
* https://github.com/google/ground-android/issues/142
* https://github.com/google/ground-android/issues/143
