### ISSUE TITLE
Export to CSV is failing with 404

### ISSUE THREAD

**Issue by atalekar** [google/ground-platform#837]
**Describe the bug**
Download csv endpoint is hitting a 404.

**To Reproduce**
1. Go to a project with data.
2. Click on layer with data.
3. Click on dowload observations
4. See 404 in new tab

**Expected behavior**
expect csv to be downloaded

**Screenshots**

![image](https://user-images.githubusercontent.com/6625516/141499385-b5fe582c-4dfe-4ae8-a193-a81ea159dd6c.png)

**Comment by gino-m** [comment]
@rachaprince Could this have something to do with the single-region deployment? It looks like Firebase Hosting is not redirecting to Cloud Functions as it should. Could you PTAL?

**Comment by rachaprince** [comment]
Yes, unfortunately this is caused by single-region deployment. From the [firebase hosting docs](
https://firebase.google.com/docs/hosting/full-config?authuser=0#rewrite-functions):

```
Important: Firebase Hosting supports Cloud Functions in us-central1 only.
```

One workaround I can think of is to call the cloud function url directly from the webapp, and pass along service credentials to   authenticate the webapp. 

I can take a look at this early tomorrow. (I'm guessing we'd want to do something similar to this: https://cloud.google.com/functions/docs/securing/authenticating#exchanging_a_self-signed_jwt_for_a_google-signed_id_token)

**Comment by rachaprince** [comment]
Hi @gino-m,

Thanks for the pointer! Replacing the`cloudFunctionsUrl` in the `environment.prod.ts` results in a 403 error. I believe this is because we are no longer hosting the function and the site on the same domain, and the CORS request is failing. 
 
 These docs (https://cloud.google.com/functions/docs/writing/http#limitations) suggest we either: 1. make the function public and handle auth within the function or 2. setup a cloud functions proxy 
 
 There's also this example function from the Firebase functions team: https://github.com/firebase/functions-samples/tree/main/authorized-https-endpoint. My plan is to try to adopt this example to our use case

**Comment by rachaprince** [comment]
Another option could be to implement the functions as Http callable functions (https://firebase.google.com/docs/functions/callable) , and then to use Firebase App Check (https://firebase.google.com/docs/app-check) to verify that the function requests come from our Firebase app

**Comment by gino-m** [comment]
Hi Rachel,

Are you able to access the hosted web app directly via the same domain
instead of the web.app shortcut? If so perhaps that would resolve the CORS
issue.

We opted not to use Callable Functions because they're no suited for
streaming requests or responses, so large imports and exports wouldn't be
possible. I found some discussion here:
https://stackoverflow.com/questions/56972994/pipe-file-read-stream-in-firebase-callable-function

HTH!

**Comment by atalekar** [comment]
Rachel prioritize this if it is easy to do - if it is too complicated it is fine if this doesn't work. We will need to reprocess this data anyways - specifically realign data across multiple layers into our internal proto format, joining based on point within polygon as well as other params. CSVs are not the most important thing as long we are capturing data correctly.

**Comment by rachaprince** [comment]
I spoke with Gino, and it seems like this will be a non-trivial amount of effort. 

Because CORS requests are unauthenticated, we'd need to make the functions public to invoke them from the web app. Then we'd need to pass along auth headers to authenticate the client. That would require a switch from export by hyperlink to export by HttpClient to be able set headers. 

So yes, I think the best path forward is to de-prioritize this for now.

**Comment by gino-m** [comment]
+1 to @rachaprince's comment. Also if we want to allow Ground to work on Firebase Spark (free plan), we may need to move import and export out of Cloud Functions and into client anyway, so this might end up being throwaway work. Hope we can work around it for this pilot.

**Comment by gino-m** [comment]
This has since been resolved.
