### ISSUE TITLE
[Code health] Simplify and error handle in Firestore data converter

### ISSUE THREAD

**Issue by os-micmec** [google/ground-platform#932]
There is a number of improvements we can make to our Firestore data conversion class.

- [ ] Split the different data conversions (LOI, Submission, etc) in their own separate classes
- [ ] Add/improve tests
- [ ] Return errors on the methods exposed by the data conversion classes

**Comment by gino-m** [comment]
@os-micmec pasting in description from duplicate #937. Please feel free to merge the two if it helps:

- [ ] Fail gracefully when bad/malformed/missing data is found in Firestore
  - [ ]  Return `Foo | Error` from public datastore methods instead of throwing Errors. (Errors ok to use internally in private methods where it increases readability).
  - [ ] Handle errors by log the issue to console and either ignoring the entity, or displaying an error in the UI where appropriate
- [ ] Split firestore-data-converter.ts into per-class converters (e.g., JobConverter, TaskConverter, etc.)
  - [ ] In the process, add missing test coverage (no round trip). Parameterized testing example in [tests in #929](https://github.com/google/ground-platform/pull/929/files#diff-ce83bf3978ee20cb9e694f687980cf972b15b13842d42c62c2d6c3f1f2917ef0R99)

**Comment by gino-m** [comment]
@DaoyuT Related to your current work on capturing auth errors

**Comment by gino-m** [comment]
We downscoped #931, so this is now a duplicate.
